#To add credentialSecretName to rancher run this. Shoud be the S3 storage loginn info.
#kubectl create secret generic s3-creds  --from-literal=accessKey=admin --from-literal=secretKey=test1234
apiVersion: resources.cattle.io/v1
kind: Backup
metadata:
  name: test-rancker-backup
  annotations:
    {}
    #  key: string
  labels:
    {}
    #  key: string
spec:
  resourceSetName: rancher-resource-set
  retentionCount: 10
  schedule: 30 2 * * *
  storageLocation:
    s3:
      bucketName: test
      credentialSecretName: s3-creds 
      credentialSecretNamespace: default
      endpoint: 10.10.10.10:443
      folder: rancher-backup1
      insecureTLSSkipVerify: true
#      endpointCA: string
#      region: string
#  encryptionConfigSecretName: string
status:
